### ISSUE TITLE
OpenBLAS issue with alternative docker image

### ISSUE THREAD

**Issue by jonmcalder** [exercism/r-test-runner#59]
After merging #56, I noticed we were seeing this OpenBLAS issue when attempting to run tests on the platform:

![Screenshot 2023-03-16 at 23 24 20](https://user-images.githubusercontent.com/5055818/225846059-411bf6fc-7c0a-4ddd-a64e-aa66e39e5b1f.png)

So we decided to revert the change for now #58 while we work on resolving the underlying issue.

Based on limited & naive research that I've done, my hunch is that setting these env variables (to 1 or some suitably low number) in the dockerfile could sidestep this issue:
```
ENV OMP_NUM_THREADS=1
ENV OPENBLAS_NUM_THREADS=1
```

But I'm not sure how to test this because the issue doesn't manifest when testing on docker locally.

@ErikSchierboom is there a way you could test this in some sort of dev / staging environment that more closely matches the production environment?

And even if the above - let's call it option (a) - does work, I'm not sure if that is the best route to go here. The source of the issue is that the `rocker/tidyverse` docker image is derived from `rocker/r-ver` which uses the OpenBLAS implementation (for Linear Algebra) as opposed to the reference implementation of BLAS which the base R image uses.

So we could alternatively look at: 
- (b) switching the BLAS implementation e.g. https://rocker-project.org/images/versioned/r-ver.html#selecting-the-blas-implementation-used-by-r
- (c) or stick with the base R docker image that we've been using until now that doesn't use OpenBLAS and install the tidyverse packages and dependencies as separate scripts steps in the dockerfile for the R test runner

Taking a look at https://rocker-project.org/images/, it's clear that the rocker versioned stack is more focused on reproducibility and thus better suited for our purposes than the base stack, so even though (c) may seem simpler on the face of it, I think that some variant of approach (a) or (b) is probably better long term.

### Other References

Somewhat relevant / related threads (which I'm sure you'll find too but just so you can get an idea what I'm basing the above on):
 
https://github.com/rocker-org/rocker/issues/417
https://github.com/rocker-org/rocker/issues/412#issuecomment-666415627
https://github.com/rocker-org/rocker-versioned2/issues/34
https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable
https://github.com/bcgsc/mavis/issues/185

FYI @DaveParr

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom is there a way you could test this in some sort of dev / staging environment that more closely matches the production environment?

I'm afraid not. And I can confirm that it (the rocker image) also worked locally. Our production setup uses AWS machines and they're configured a lot differently. Maybe we should try a PR that implements a), see if it works and if it doesn't, revert?

**Comment by DaveParr** [comment]
@ErikSchierboom thanks for all your work (and @jonmcalder) on this. If this turns into a 'too complicated to achieve' kinda problem I won't hold it against you :)
